
version: '3.6'
services:
  mysql:
    image: mysql:latest
    container_name: mysql_spring
    command: --default-authentication-plugin=mysql_native_password --sql_mode=''
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: med
      MYSQL_USER: med
      MYSQL_PASSWORD: 123456
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql: